### PR TITLE
[ON HOLD] Propagate parameters from jQuery success/error/copmplete callbacks to onAfter[x] callbacks v2

### PR DESCRIPTION
**Pull request by prantlf**
Additionally, call the onAfter[x] callbacks before the original jQuery ones.  This may be a breaking change if somebody depended on the original jQuery callbacks executed earlier.

This suggest a resolution for the first half of the #225.

### CODE REVIEW

**Comment by jakerella** [comment]
I think I see the need for reordering the method calls here, but I want to get another pair of :eyes:  on it before merging. (And I'm totally fine with adding the original jQuery arguments.

@dcneiner, can you take a look? Note that this helps enable #233, although it is technically separate functionality.

**Comment by jakerella** [comment]
@dcneiner Any chance you can review this change soon?

@prantlf Looks like a conflict crept in from recent changes, but my guess is the conflict is small considering your changes. Can you resolve?

**Comment by dcneiner** [comment]
@jakerella Looking now!

**Comment by dcneiner** [comment]
Ok, first off, thank you @prantlf for all the thought and work you put into this feature. I think having the ability to pre-process the response seems like a great idea, and passing through the original jQuery arguments also is a great idea,

I do think keeping the names as `onAfterSuccess` but having it fire before the normal handler is a problem. This got me to thinking, it would be fairly straightforward to keep the existing `onAfter{...}` callbacks and add new `onBefore` callbacks for usage as you suggested. 

If @jakerella agrees, would you be willing to try and tackle that change? Let us know if you need any help.

**Comment by dcneiner** [comment]
Oh, I forgot to mention – the conflicts seem to be just the built version of mockjax. So resolving it should be pretty easy.

**Comment by jakerella** [comment]
Hey @prantlf: any chance you can get to this PR (and maybe the other one) this week? I'm planning to release 2.0.0-beta this week/weekend and would love to include this. If not, we can plan for including it in 2.1.0, which shouldn't be too far behind.

**Comment by jakerella** [comment]
Last chance for 2.0.0... but we can always get it into 2.1.0.

**Comment by jakerella** [comment]
Placed on hold pending conversion to 2.x

**Comment by jakerella** [comment]
Closing this PR for inactivity. The issue is still there, and the code is on a good path. Any new PR would need to be merged into `master` at this point.

**Pull request closed without merging**
