### PR TITLE
Add wrapper for AMDJS, CommonJS and browser modules

### PR DESCRIPTION
**Pull request by prantlf**
Adds wrapping factory function recognizing the three environments and plugging the mockjax into jQuery accordingly.

Includes just this change an no other refactoring.

Uses the [universal module pattern](https://github.com/umdjs/umd) and the name 'jquery' for the jQuery module dependency.

### CODE REVIEW

**Comment by jakerella** [comment]
Thanks for taking this, unfortunately this is on the roadmap for 2.0.0 and won't be implemented in the `1.x` branch. Ca you do this work on the `v2` branch and send a PR for that? We also need to be sure to run this with all current tests (which use the `<script>` inclusion method) and then create tests for the other forms of importing (CommonJS and AMD).

**Comment by prantlf** [comment]
You're welcome.  I'll create another PR for the v2 branch.  The current tests run "green".  I'll try adding loading tests too when the time permits.

**Comment by prantlf** [comment]
I created #229 with this change against the v2 branch.  Another PR - #230 - contains init tests for AMD using Require.js.  Yet another PR - #231 - tests the CommonJS interface in Node.js.   This PR can be probably closed.

**Comment by jakerella** [comment]
Closing this issue for now. We will not be integrating AMD/UMD into the 1.x branch.

**Pull request closed without merging**
