### PR TITLE
Get crossdomain GET hack patch in /src instead of /dist

### PR DESCRIPTION
**Pull request by r4j4h**
To help #136

### CODE REVIEW

**Comment by r4j4h** [comment]
Bah I didn't want to commit anything to /dist but didn't want to remove LeopoldoFu's contribution. Let me know and I can get that out of the mr if it's a problem.

**Comment by jakerella** [comment]
Well, the real issue is that this only works for `GET`... I'd like to find a solution that works for all methods.

**Comment by r4j4h** [comment]
Yeah, that makes sense. I noticed the existing merge request mentioned in the thread only affected the file in the dist directory so it would be overwritten when the code is built. Hopefully it will help anybody who needs it until a better solution is found. I agree that it should not be merged in until then for that reason.

**Comment by r4j4h** [comment]
As an update we found we actually didn't have an issue at all with mockjax in this case but our mocking library was keeping a setTimeout from executing.

**Comment by jakerella** [comment]
Good to hear. I'm actually going to close this PR as the issue is still open and I think this is only a partial fix (or not one at all).

**Pull request closed without merging**
