### PR TITLE
Update bower.json to allow ES6 importing

### PR DESCRIPTION
**Pull request by bt**
By updating the `main` key, of `bower.json`, ES6 can import mockjax with just the following code:

```
import 'jquery-mockjax';
```

### CODE REVIEW

**Comment by bt** [comment]
Sorry! Didn't see the comments for CommonJS loading!

**Comment by bt** [comment]
Actually, I just tried and it seems that without the changes I made, within webpack, I would have to require it like this:

```
require('jquery-mockjax/dist/jquery.mockjax')(jQuery, window);
```

With my changes, you can require it with just this:

```
require('jquery-mockjax')(jQuery, window);
```

Given that it's a singular file in the `main` key, it may just be best to refer to just it?

**Comment by jakerella** [comment]
Looks like the [spec does support a string value](https://github.com/bower/spec/blob/master/json.md#main) for the `main` entry, and since we only one file, I'm cool with this. I'll leave it for a bit to see if @dcneiner has any comments, but otherwise I'll merge it in.

**Comment by bt** [comment]
Any updates? Just going through a refactor of my company's code and I just wanted to close off this "todo" item 😄

**Comment by jakerella** [comment]
I usually let PRs sit for a bit to allow for any other comments. Since we've only been letting this sit over the weekend I'm going to give it a couple days of the work week. If there is no comment, I'll merge it in later this week.

**Comment by bt** [comment]
No worries! Good to hear that it'll be moving along 😄

**Comment by kamrenz** [comment]
@bt I am trying your initial work around: 
```
require('jquery-mockjax/dist/jquery.mockjax')(jQuery, window); 
```
but am getting the following error:
```
ERROR in ./~/jquery-mockjax/dist/jquery.mockjax.js
Unexpected token (17:3)
You may need an appropriate loader to handle this file type.
```
Do you have any special config setup in your webpack.config.js for jquery-mockjax?

**Comment by kamrenz** [comment]
@bt I have been having an issue... see https://github.com/jakerella/jquery-mockjax/issues/285

**Comment by bt** [comment]
Hey kamrenz,

You might not get much value out of this PR because it's only changed in the bower.json file, and I assume you're using NPM.

I have this in my Webpack configuration, which allows me to load bower components:

```
    resolve: {
        modulesDirectories: [
            'src',
            'node_modules',
            'bower_components'
        ],
        extensions: ['', '.json', '.js']
    },
    plugins: [
        new webpack.ResolverPlugin([
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('package.json', ['main']),
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
        ])
    ]
```

And.. can you confirm you have a .js loader for your Webpack like this:

```
        loaders: [
            {
                test: /\.js$/,
                exclude: [
                    /node_modules/,
                    /bower_components/
                ],
                loaders: ['babel?' + JSON.stringify(babelrcObject), 'eslint-loader']
            }
```

**Comment by kamrenz** [comment]
I don't have that JS loader... When running it I am getting:
```
babelrcObject is not defined
```
My project isn't using babel at this point. Simple AMD modules.

**Comment by bt** [comment]
You'll probably want to use the [script-loader](https://github.com/webpack/script-loader) then.

**Comment by kamrenz** [comment]
I needed to add an imports loader directly to the jquery-mockjax file in my config.
```
module: {
  loaders: [ 
  {           
    test: /jquery.mockjax.js$/,
    loader: 'imports?jQuery=jquery'
  }
}
```
Then I could utilize jquery-mockjax in my defined array of dependencies
```
define([
	'jquery',
	'jquery-mockjax'
], function($) {
  //... stuff
});

**Comment by bt** [comment]
Oh I see. I solved that issue by the following:

```
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        })
    ]
```

That way I can use $ (jQuery) throughout my modules.

**Comment by kamrenz** [comment]
Yeah. I thought that would solve the issue early on, but it didn't. I have some other scripts that I needed to use the Provide Plugin for, but it didn't work with jquery-mockjax...

**Comment by kamrenz** [comment]
FYI @jakerella @bt's issue about Bower is similar to NPM. When using jquery-mockjax, Webpack is automatically pulling in the JS file from src instead of dist.

**Comment by jakerella** [comment]
Yep... that's because of the `main` entry in the package.json file. However, I'm not sure if we want to change that. The thing is, for Node, that's the file we want... That's what I want to run my main tests against. I'll give this some thought, but feel free to open a new issue if you feel the need.

**Comment by bt** [comment]
@jakerella In this case, given that is the main file, should the bower.json file not reference the same file then?

I am happy to make a new PR for that 👍

**Pull request merged**
