### PR TITLE
Changed to using $.ajaxSetup to fix depp copy issue

### PR DESCRIPTION
**Pull request by jakerella**
Please read #74 for the explanation of the need for this change. If you read the jQuery source for [`$.ajaxSetup()`](https://github.com/jquery/jquery/blob/1.11-stable/src/ajax.js#L367-L375) (and the [internal `ajaxExtend()` function](https://github.com/jquery/jquery/blob/1.11-stable/src/ajax.js#L122) you can see that this is really just a light wrapper around `$.extend()` for ajax options that are explicitly marked as "flat". Tests are running fine with the change.

Note that the other places we use `$.extend()` should not have any issues.

### CODE REVIEW

**Comment by jakerella** [comment]
ping @dcneiner 

Any concerns?

**Comment by jakerella** [comment]
Ok @dcneiner ... merging tomorrow one way or another :)

**Comment by dcneiner** [comment]
@jakerella Looking into this, please don't merge just yet…

**Comment by dcneiner** [comment]
@jakerella Never mind, looks good! Didn't realize the behavior changed in that way – and its still not documented on their API site to support the target. :+1:

**Comment by jakerella** [comment]
:)

**Pull request merged**
