### PR TITLE
[ON HOLD] Enable passing through the requests to the original URL v2

### PR DESCRIPTION
**Pull request by prantlf**
If `passThrough` is `true`, performs the request with the original settings and lets the onAfter[x] callback modify the response:

```
$.mockjax({
  url: '/api/currentuser',
  passThrough: true,
  onAfterSuccess: function (response) {
    response.image = '/images/profile';
  }
});
```

This suggest a resolution for the second half of the #225.

### CODE REVIEW

**Comment by jakerella** [comment]
@dcneiner Can you review this one as well?

@prantlf Same as the other PR, looks like some small conflicts crept in. Can you resolve?

**Comment by dcneiner** [comment]
@prantlf @jakerella Please see my comments on #232, as that will impact this PR some. I think this PR looks good, though I'd recommend renaming the function variable `passThroughCallbacks` to something that reflects its more generic usage. Perhaps `wrapCallbacks` or something you like better.

Thanks again for your work on this!

**Comment by jakerella** [comment]
On hold until conflicts can be resolved.

**Comment by jakerella** [comment]
Closing this PR for inactivity. The issue is still there, and the code is on a good path. Any new PR would need to be merged into `master` at this point.

**Pull request closed without merging**
