### PR TITLE
fix: remove undefined `head` variable

### PR DESCRIPTION
**Pull request by GuruM**
This undefined variable causes JSONP requests to fail.

### CODE REVIEW

**Comment by jakerella** [comment]
Ugh... looks like a leftover remnant of a previous way of doing things. I'll pull this in, but can you please submit a separate PR to the `v2` branch?

Thanks!

**Comment by jakerella** [comment]
@dcneiner Does this look like just a remnant to you as well? Am I missing anything here?

**Comment by GuruM** [comment]
@jakerella at your service: #235

**Comment by jakerella** [comment]
Okay... I'm gonna pull this one in, I can't find any reference to that variable other than the removed lines.

**Pull request merged**
